//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManagerv1.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManagerv1.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page.
        /// </summary>
        internal static string AirbnbDomesticPageTitle {
            get {
                return ResourceManager.GetString("AirbnbDomesticPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page.
        /// </summary>
        internal static string AirbnbInternationalPageTitle {
            get {
                return ResourceManager.GetString("AirbnbInternationalPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button pressed: .
        /// </summary>
        internal static string ButtonPressed {
            get {
                return ResourceManager.GetString("ButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        internal static string DomesticText {
            get {
                return ResourceManager.GetString("DomesticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page.
        /// </summary>
        internal static string FacebookPageTitle {
            get {
                return ResourceManager.GetString("FacebookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Page.
        /// </summary>
        internal static string InstagramPageTitle {
            get {
                return ResourceManager.GetString("InstagramPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string InternationalText {
            get {
                return ResourceManager.GetString("InternationalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotype.
        /// </summary>
        internal static string LogotypeText {
            get {
                return ResourceManager.GetString("LogotypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World! Welcome to MAUI.
        /// </summary>
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats App Page.
        /// </summary>
        internal static string WhatsAppPageTitle {
            get {
                return ResourceManager.GetString("WhatsAppPageTitle", resourceCulture);
            }
        }
    }
}
